Update to catch v2.13.10, which fixes https://github.com/catchorg/Catch2/issues/2178 :
catch.hpp:10822:58: error: call to non-'constexpr' function 'long int sysconf(int)'

followed by:

catch.hpp:10881:45: error: size of array 'altStackMem' is not an integral constant-expression